import os
from selene import browser, be, have, command

def test_fill_and_send():
    browser.open('/automation-practice-form')
    browser.should(have.title('DEMOQA'))
    browser.element('.text-center').should(have.text('Practice Form'))
    browser.element('#firstName').should(be.blank).type('Akhil')
    browser.element('#lastName').should(be.blank).type('Nadar')
    browser.element('#userEmail').should(be.blank).type('nadar@test.in')
    browser.all('[type="radio"]').should(have.size(3))
    browser.element('[for="gender-radio-1"]').should(have.text('Male')).click()
    browser.element('#userNumber').should(be.blank).type('9112345678')
    # browser.element('#dateOfBirthInput').perform(command.select_all).type('31 Jul 1992').press_enter()
    browser.element('#dateOfBirthInput').click()
    browser.element('.react-datepicker__year-select').click().element('option[value="1992"]').click()
    browser.element('.react-datepicker__month-select').click().element('option[value="6"]').click()
    browser.element('.react-datepicker__day--031').click()
    browser.element('#subjectsInput').should(be.blank).type('Maths').press_enter().type('Physics').press_enter()
    browser.all('[type="checkbox"]').should(have.size(3))
    browser.element('[for="hobbies-checkbox-1"]').should(have.text('Sports')).click()
    browser.element('[for="hobbies-checkbox-2"]').should(have.text('Reading')).click()
    browser.element('#uploadPicture').send_keys(f'{os.getcwd()}/downloads/460.jpg')
    browser.element('#currentAddress').should(be.blank).type('14, Ashoka Rd, Sansad Marg Area')
    browser.element('#react-select-3-input').type('NCR').press_enter()
    browser.element('#react-select-4-input').type('Delhi').press_enter()
    browser.element('#submit').perform(command.js.scroll_into_view).click()
    
    browser.element('.modal-title.h4').should(have.text('Thanks for submitting the form'))
    browser.element('.//tbody/tr[td="Student Name"]').should(have.text('Akhil Nadar'))
    browser.element('.//tbody/tr[td="Student Email"]').should(have.text('nadar@test.in'))
    browser.element('.//tbody/tr[td="Gender"]').should(have.text('Male'))
    browser.element('.//tbody/tr[td="Mobile"]').should(have.text('9112345678'))
    browser.element('.//tbody/tr[td="Date of Birth"]').should(have.text('31 July,1992'))
    browser.element('.//tbody/tr[td="Subjects"]').should(have.text('Maths, Physics'))
    browser.element('.//tbody/tr[td="Hobbies"]').should(have.text('Sports, Reading'))
    browser.element('.//tbody/tr[td="Picture"]').should(have.text('460.jpg'))
    browser.element('.//tbody/tr[td="Address"]').should(have.text('14, Ashoka Rd, Sansad Marg Area'))
    browser.element('.//tbody/tr[td="State and City"]').should(have.text('NCR Delhi'))
    
